@startuml
class com.opencsv.CSVReader
class com.opencsv.CSVWriter
class java.io.BufferedReader
class java.io.File
class java.io.FileInputStream
class java.io.FileReader
class java.io.FileWriter
class java.io.IOException
class java.io.InputStreamReader
class java.nio.file.Path
class java.nio.file.Paths
class java.util.ArrayList
class java.util.Formatter
class java.util.HashMap
class java.util.Iterator
class java.util.List
class java.util.ListIterator
class java.util.Map.Entry
class java.util.logging.Level
class java.util.logging.Logger
class javafx.application.Application
class javafx.application.Platform
class javafx.beans.InvalidationListener
class javafx.beans.Observable
class javafx.event.ActionEvent
class javafx.event.EventHandler
class javafx.fxml.FXMLLoader
class javafx.geometry.Insets
class javafx.scene.Scene
class javafx.scene.control.Button
class javafx.scene.control.Label
class javafx.scene.control.ListView
class javafx.scene.control.Slider
class javafx.scene.control.TextField
class javafx.scene.image.Image
class javafx.scene.image.ImageView
class javafx.scene.input.MouseEvent
class javafx.scene.layout.HBox
class javafx.scene.layout.VBox
class javafx.scene.media.Media
class javafx.scene.media.MediaPlayer
class javafx.scene.media.MediaPlayer.Status
class javafx.scene.media.MediaView
class javafx.scene.text.Font
class javafx.stage.FileChooser
class javafx.stage.Stage
class javafx.util.Duration
class javax.swing.JOptionPane
class musicplayer.MusicPlayer
class musicplayer.controller.ButtonController
class musicplayer.controller.CSVHandler
class musicplayer.controller.Controller
class musicplayer.model.AVL
class musicplayer.model.Playlist
class musicplayer.model.Song
class musicplayer.view.View
@enduml